services:
  mongo:
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - '27017:27017'
    env-file:
      - .env
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
    driver: local
